atmworks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

main_app/urls.py
from django.urls import path
from . import views


# URLS GO HERE

# Home page URL
urlpatterns = [
    path('', views.home, name='home'),

    # About page
    path('about/', views.about, name='about'),
    path('accounts/signup/', views.signup, name='signup'),
    path('atms/', views.atms_index, name='index'),
    path('atms/<int:atm_id>/', views.atms_detail, name='detail'),
    path('atms/create/', views.AtmCreate.as_view(), name='atms_create'),
    path('atms/<int:pk>/update/', views.AtmUpdate.as_view(), name='atms_update'),
    path('atms/<int:pk>/delete/', views.AtmDelete.as_view(), name='atms_delete'),

    # REVENUE
    path('atms/<int:atm_id>/add_revenue',
         views.add_revenue, name='add_revenue'),
    path('atms/revenue/<int:pk>/delete/',
         views.DeleteRevenue.as_view(), name='revenue_delete'),


    # CASH INPUTS
    path('atms/<int:atm_id>/add_cashinput',
         views.add_cashinput, name='add_cashinput'),
    path('atms/cashinput/<int:pk>/delete/',
         views.DeleteCashinput.as_view(), name='cashinput_delete'),


    # MAPBOX STUFF
    path('map/', views.map, name='map'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# GEOCODER MAPBOX
import geocoder

access_token = 'pk.eyJ1IjoiYXRtd29ya3MiLCJhIjoiY2xjcHE4Z2FxNGs0ODNxcDRyaWxybGNpcCJ9.D3CXUrooyNKlRV62OY6EIQ'



# Create your models here.


class Atm(models.Model):
    name = models.CharField(max_length=100)
    location_type = models.CharField(max_length=50)
    business_fee = models.IntegerField()
    surcharge = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    address = models.CharField(max_length=100)
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)

    # add geo coder converter to convert address to lon and lat

    def save(self, *args, **kwargs):
        g = geocoder.mapbox(self.address, key=access_token)
        g = g.latlng
        self.lat = g[0]
        self.long = g[1]
        return super(Atm, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'atm_id': self.id})


class Revenue(models.Model):
    date = models.DateField()
    amount = models.IntegerField()
    # yearly = models.IntegerField()

    atm = models.ForeignKey(Atm, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']



class CashInput(models.Model):
    date = models.DateField('Date Cash Added')
    amount = models.IntegerField()

    atm = models.ForeignKey(Atm, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']

    

# MAPBOX ADDRESS MODEEL

main_app/forms.py
from django.forms import ModelForm
from .models import Revenue, CashInput
from crispy_forms.helper import FormHelper
from django import forms

class RevenueForm(ModelForm):
  class Meta:
    model = Revenue
    fields = ['date', 'amount']
    widgets = {
        'date': forms.DateInput(attrs={'type': 'date'})
    }


class CashInputForm(ModelForm):
  class Meta:
    model = CashInput
    fields = ['date', 'amount']
    widgets = {
        'date': forms.DateInput(attrs={'type': 'date'})
    }

main_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Atm, Revenue, CashInput
from .forms import RevenueForm, CashInputForm

from django.http import HttpResponseRedirect

# Create your views here.

# Home


def home(request):
    return render(request, 'home.html')

# About


def about(request):
    return render(request, 'about.html')

# MAP views
def map(request):
    atms = Atm.objects.filter(user=request.user)
    return render(request, 'mapbox/map.html', {'atms': atms})


class AtmCreate(LoginRequiredMixin, CreateView):
    model = Atm

    fields = ['name', 'location_type', 'address', 'business_fee', 'surcharge']

# assings atm to a user I believe
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)



class AtmUpdate(LoginRequiredMixin, UpdateView):
    model = Atm
    fields = ['name', 'location_type', 'address', 'business_fee', 'surcharge']


class AtmDelete(LoginRequiredMixin, DeleteView):
    model = Atm
    success_url = '/atms/'


def signup(request):
    error_message = ''
    if request.method == 'POST':

        form = UserCreationForm(request.POST)
        if form.is_valid():

            user = form.save()

            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'

    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


# The ability to show only the user's ATMs as this is sensitive financial data. Decorating a lot to protect these.
@login_required
def atms_index(request):
    atms = Atm.objects.filter(user=request.user)
    return render(request, 'atms/index.html', {'atms': atms})


@login_required
def atms_detail(request, atm_id):

    atm = Atm.objects.get(id=atm_id)

    cashinput_form = CashInputForm()
    revenue_form = RevenueForm()

    return render(request, 'atms/detail.html', {'atm': atm, 'revenue_form': revenue_form, 'cashinput_form': cashinput_form})


# REVENUE STUFF

@login_required
def add_revenue(request, atm_id):
    form = RevenueForm(request.POST)
    # validdate form
    if form.is_valid():
        # don't save the form to the db until it
        # has the atm_id assigned
        new_revenue = form.save(commit=False)
        new_revenue.atm_id = atm_id
        new_revenue.save()
    return redirect('detail', atm_id=atm_id)

# DELETE REVENUE


class DeleteRevenue(LoginRequiredMixin, DeleteView):
    model = Revenue

    def get_success_url(self):
        atm = self.object.atm
        return reverse_lazy('detail', kwargs={'atm_id': atm.id})

    # success_url = get_absolute_url
    # def get_success_url(request, atm_id):
    #     return HttpResponseRedirect(reverse('/atms/', kwargs={atm_id:atm_id}))


# CASH INPUT STUFF
@login_required
def add_cashinput(request, atm_id):
    form = CashInputForm(request.POST)
    # validdate form
    if form.is_valid():
        # don't save the form to the db until it
        # has the atm_id assigned
        new_cashinput = form.save(commit=False)
        new_cashinput.atm_id = atm_id
        new_cashinput.save()
    return redirect('detail', atm_id=atm_id)


class DeleteCashinput(LoginRequiredMixin, DeleteView):
    model = CashInput

    def get_success_url(self):
        atm = self.object.atm
        return reverse_lazy('detail', kwargs={'atm_id': atm.id})


# MAPBOX STUFF

# class AddressView(CreateView):
#     model = Address
#     fields = ['address']
#     template_name = 'mapbox/map.html'
#     success_url = '/map/'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['addresses'] = Address.objects.all()
#         return context



# assign address to a user i believe
    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     return super().form_valid(form)

main_app/templates/about.html
{% comment %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://kit.fontawesome.com/bce51483a3.js"
      crossorigin="anonymous"
    ></script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Jost&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon.ico' %}"
    />
    <!-- MAPBOX STUFF -->

    <script src="https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.js"></script>
    <link
      href="https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.css"
      rel="stylesheet"
    />

    {% load crispy_forms_tags %}
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <!-- Container wrapper -->
      <div class="container">
        <!-- Toggle button -->
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Navbar brand -->
          <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'home' %}">
            <!-- <h2>ATM-WORKS</h2> -->
            <img
              src="https://imgur.com/cfl7TTD.png"
              height="45"
              alt="MDB Logo"
              loading="lazy"
            />
          </a>
          <!-- Left links -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="https://atmworks.fly.dev/#start-about"
                >About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">ATM Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://atmworks.fly.dev/#team-container"
                >Team</a
              >
            </li>
            <!-- <li class="nav-item"><a class="nav-link" href="{% url 'atms_create' %}">New ATM Here</a></li> -->
            <!-- <li class="nav-item" ><a class="nav-link" href="{% url 'index' %}">View All ATMs</a></li> -->
          </ul>
          <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->

        <!-- Right elements -->

        <div class="d-flex align-items-center">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
          <!-- Avatar -->
          <div class="dropdown">
            <a
              class="dropdown-toggle d-flex align-items-center hidden-arrow"
              href="#"
              id="navbarDropdownMenuAvatar"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              <img
                src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
                class="rounded-circle"
                height="30"
                alt="Black and White Portrait of a Man"
                loading="lazy"
              />
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuAvatar"
            >
              <li>
                <a class="dropdown-item" href="#">My profile</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Settings</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'login' %}">Logout</a>
              </li>
            </ul>
          </div>
        </div>
        <!-- Right elements -->
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    <!-- Row -->

    <div class="container">
      <h1>MAP GOES HERE??</h1>

      <div id="map" style="width: 100%; height: 600px"></div>
      <script>
        mapboxgl.accessToken =
          "pk.eyJ1IjoiYXRtd29ya3MiLCJhIjoiY2xjcHE4Z2FxNGs0ODNxcDRyaWxybGNpcCJ9.D3CXUrooyNKlRV62OY6EIQ";


        const map = new mapboxgl.Map({
          container: "map", // container ID
          style: "mapbox://styles/mapbox/streets-v12", // style URL
          center: [-74.5, 40], // starting position [lng, lat]
          zoom: 6, // starting zoom
        });

        {% for address in addresses %}
        // Create a new marker.
        const marker = new mapboxgl.Marker()
            .setLngLat([ {{ address.long }}, {{ address.lat }}])
            .addTo(map);
        
        {% endfor %}

      </script>
    </div>
  </body>
</html> {% endcomment %}

main_app/templates/atms/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://kit.fontawesome.com/bce51483a3.js"
      crossorigin="anonymous"
    ></script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Jost&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% load crispy_forms_tags %}
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <!-- Container wrapper -->
      <div class="container">
        <!-- Toggle button -->
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Navbar brand -->
          <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'home' %}">
            <!-- <h2>ATM-WORKS</h2> -->
            <img
              src="https://imgur.com/cfl7TTD.png"
              height="45"
              alt="MDB Logo"
              loading="lazy"
            />
          </a>
          <!-- Left links -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="https://atmworks.fly.dev/#start-about"
                >About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://atmworks.fly.dev/#team-container">Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'atms_create' %}"
                >New ATM Here</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">View All ATMs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'map' %}">Map View</a>
            </li>
          </ul>
          <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->

        <!-- Right elements -->

        <div class="d-flex align-items-center">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
          <!-- Avatar -->
          <div class="dropdown">
           
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuAvatar"
            >
              <li>
                <a class="dropdown-item" href="#">My profile</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Settings</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'login' %}">Logout</a>
              </li>
            </ul>
          </div>
        </div>
        <!-- Right elements -->
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    <!-- Row -->

    <title>How Is This ATM Performing?</title>
    <div class="container">
      <h1 class="text-center">This ATM's Performance:</h1>
      <div class="row">
        <div class="col s12">
          <div class="card">
            <div class="card-body text-center">
              <h3 class="card-title">Name: {{ atm.name }}</h3>
              <p>Location: {{ atm.location_type }}</p>
              <p>Address: {{ atm.address }}</p>
              <p>Business Fee: ${{ atm.business_fee}}</p>
              <p>Surcharge: ${{ atm.surcharge}}</p>
            </div>
            <div class="card-action ml-2 mb-2 text-center">
              <a class="btn btn-secondary" href="{% url 'atms_update' atm.id %}"
                >Edit</a
              >
              <a class="btn btn-danger" href="{% url 'atms_delete' atm.id %}"
                >Delete</a
              >
            </div>
          </div>
        </div>
      </div>
<br>
      <div class="row">
        <div class="col s6">
          <!-- new code below -->
          <form method="post" action="{% url 'add_revenue' atm.id %}">
            {% csrf_token %}
            {{ revenue_form|crispy }}
            <br>
            <input
              type="submit"
              class="btn btn-success"
              value="Add Monthly Revenue"
            />
          </form>
          <!-- NEW FORM BELOW -->
<br>
<br>
          <!-- new code above -->
          <table class="table">
            <thead class="table-dark">
              <tr>
                <th>Date</th>
                <th>Monthly Revenue</th>
                <th>Delete</th>
              </tr>
            </thead>
            <tbody>
              {% for revenue in atm.revenue_set.all %}
              <tr>
                <td>{{revenue.date}}</td>
                <td>${{revenue.amount}}</td>
                <td>
                  <form
                    action="{% url 'revenue_delete' revenue.id %}"
                    method="POST"
                  >
                    {% csrf_token %}
                    <input type="submit" value="X" class="btn text-danger" />
                  </form>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
<br>
        <div class="col s6">
          <form method="post" action="{% url 'add_cashinput' atm.id %}">
            {% csrf_token %} 
            {{ cashinput_form|crispy }}
            <br>
            <input
              type="submit"
              class="btn btn-success"
              value="Add Cash Input"
            />
          </form>
<br>
<br>
          <table class="table">
            <thead class="table-dark">
              <tr>
                <th>Date</th>
                <th>Cash Input</th>
                <th>Delete</th>
              </tr>
            </thead>
            <tbody>
              {% for cashinput in atm.cashinput_set.all %}
              <tr>
                <td>{{cashinput.date}}</td>
                <td>${{cashinput.amount}}</td>
                <td>
                  <form
                    action="{% url 'cashinput_delete' cashinput.id %}"
                    method="POST"
                  >
                    {% csrf_token %}
                    <input type="submit" value="X" class="btn text-danger" />
                  </form>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </body>
</html>

main_app/templates/main_app/atm_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<div class="container">
<h1>Delete ATM</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn btn-danger" />
  <a href="{% url 'detail' atm.id %}">Cancel</a>
</form>

<br>

</div>
{% endblock %}

main_app/templates/main_app/atm_form.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  {% if object %}
  <h1>Edit Details For <span class="teal-text">{{ object.name }}</span></h1>
  {% else %}
  <h1>Add ATM</h1>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form|crispy }}
    </table>
    <br>
    <input type="submit" class="btn btn-success" value="Submit!" />
  </form>

<br>
</div>

{% endblock content %}

main_app/templates/main_app/revenue_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Revenue</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' revenue.id %}">Cancel</a>
</form>
{% endblock %}